const ROLES = {
  HQ_SAFETY_OFFICER: 'HQ_SAFETY_OFFICER',
  FIELD_SAFETY_OFFICER: 'FIELD_SAFETY_OFFICER',
  SAFETY_SUPERVISOR: 'SAFETY_SUPERVISOR',
  TOP_MANAGEMENT: 'TOP_MANAGEMENT'
};

module.exports = {
  ROLES,
  ALL_ROLES: Object.values(ROLES)
};
